# Script usage description
usage(){
    (
    echo -e "Basic usage:"
    echo -e "       ${yellow}$0${reset} ${green}-d domain.com -wsd -wtd curl${reset}"
    echo -e "       ${yellow}$0${reset} ${green}-dl /path/file/domain_list.txt -wsd -wtd curl${reset}"
    echo -e "       ${yellow}$0${reset} ${green}-u http://domain.com${reset}\n"
    echo "Options: "
    echo -e "\t-d  |--domain               - Specify a valid domain [${red}needed${reset}]."
    echo -e "\t-dl |--domain-list          - Specify a valid domain [${red}needed${reset}]."
    echo -e "\t-e  |--exclude-domains      - Specify excluded subdomains after all treated files [${red}used only with -d|--domain${reset}]:"
    echo -e "\t-el |--exclude-domains-list - Specify excluded subdomains from a file after all treated files [${red}used only with -d|--domain${reset}]:"
    echo -e "\t\t\t\t      use ${yellow}-e domain1.com,domain2.com${reset} OR ${yellow}--exclude-domains domain1.com,domain2.com${reset}"
    echo -e "\t-k  |--kill                 - Will kill the current execution of collector, you need to specify the domain as argument."
    echo -e "\t-ka |--kill-all             - Will kill the current execution of collector and delete the directory of results from current execution, you need to specify the domain as argument."
    echo -e "\t-l  |--limit-urls           - Specify the url quantity to run dirsearch and gobuster for dirs and files enumeration [${red}used only with -d|--domain${reset}]:"
    echo -e "\t\t\t\t      use ${yellow}-l 10${reset} OR ${yellow}--limit-urls 10${reset}"
    echo -e "\t-o  |--output               - This option when specified will use the directory to save the output of collector script if omitted the default value is:"
    echo -e "\t\t\t\t      ${yellow}${PWD}${reset}"
    echo -e "\t\t\t\t    - This option as well as others can be configured on collector.cfg, variable output_dir or use the parameters like:"
    echo -e "\t\t\t\t      use ${yellow}-o /path/of/output${reset} OR ${yellow}--output-dir /path/of/output${reset}"
    echo -e "\t-p  |--proxy                - This option will use a provided proxy (with port) to avoid or bypass WAF block."
    echo -e "\t\t\t\t      use ${yellow}-p${reset} OR ${yellow}--proxy${reset}"
    echo -e "\t-r  |--recon                - Will execute a recon until you find out what domains are web application: ${red}used only with${reset} ${yellow}-d|--domain${reset}"
    echo -e "\t\t\t\t      The web_data function will be ignored, and the recon execution will be finished."
    echo -e "\t-s  |--subdomain-brute      - Specify the wordlist to put in dns_wordlist array and execute gobuster and dnssearch brute force [${red}used only with -d|--domain${reset}]"
    echo -e "\t\t\t\t      by default the array is empty and not execute amass, gobuster and dnssearch. This option take a long time to finish, use this own your need!"
    echo -e "\t\t\t\t      The success of use those tools is a good wordlist:"
    echo -e "\t\t\t\t      use ${yellow}-s /path/to/wordlist1,/path/to/wordlist2${reset} OR ${yellow}--subdomain-brute /path/to/wordlist1,/path/to/wordlist2${reset}"
    echo -e "\t-u  |--url                  - Specify a valid url [${red}needed${reset}]."
    echo -e "\t-wd |--web-data             - Will execute a web data dig after execution of collector with recon option (${red}-re|--recon${reset}): used only with ${red}-d|--domain${reset} WITHOUT ${red}-re|--recon${reset}."
    echo -e "\t-wld|--web-long-detection   - Will execute the long list of ports setup in collector.cfg as variable web_port_long_detection." 
    echo -e "\t-wsd|--web-short-detection  - Will execute the short list of ports setup in collector.cfg as variable web_port_short_detection."
    echo -e "\t-wtd|--web-tool-detection   - You need to inform what tool to perform web application detection the tool can be ${bold}${yellow}curl${reset}${normal} OR ${bold}${yellow}httpx${reset}${normal}."
    echo -e "\t-ww |--web-wordlists        - Specity more wordlists to put in web_wordlist array"
    echo -e "\t\t\t\t      as the first wordlist to enumerate dirs and files from website."
    echo -e "\t\t\t\t      use ${yellow}-ww /path/to/wordlist1,/path/to/wordlist2${reset} OR ${yellow}--web-wordlists /path/to/wordlist1,/path/to/wordlist2${reset}"
    echo ""
    ) 1>&2; exit 1
}

