# Script usage description
usage(){
    (
    echo "Basic usage:"
    echo -e "       ${yellow}$0${reset} ${green}-d domain.com --recon${reset}"
    echo -e "       ${yellow}$0${reset} ${green}-dl /path/file/domain_list.txt --recon${reset}"
    echo -e "       ${yellow}$0${reset} ${green}-u http://domain.com --webapp-wordlists /path/file/wordlist.txt${reset}"
    echo ""
    echo "Options: "
    echo -e "\t-d  |--domain                 - Specify a valid domain [${red}needed${reset}]."
    echo -e "\t-dl |--domain-list            - Specify a valid domain [${red}needed${reset}]."
    echo -e "\t-dr |--dry-run                - Validate configuration and pre-flight checks without executing any recon."
    echo -e "\t\t\t\t        Prints target, wordlists, port detection, proxy settings, and exits."
    echo -e "\t-ed |--exclude-domain         - Specify excluded subdomains after all treated files, ${red}used only with${reset} ${yellow}-d|--domain${reset}:"
    echo -e "\t\t\t\t        use ${yellow}-e domain1.com,domain2.com${reset} OR ${yellow}--exclude-domains domain1.com,domain2.com${reset}"
    echo -e "\t-el |--exclude-domain-list    - Specify excluded subdomains from a file after all treated files, ${red}used only with${reset} ${yellow}-d|--domain${reset} or ${yellow}-dl|--domain-list${reset}:"
    echo -e "\t\t\t\t        use ${yellow}-el /path/file/excluded_domains_list.txt${reset} OR ${yellow}--exclude-domain-list /path/file/excluded_domains_list.txt${reset}"
    echo -e "\t-l  |--limit-urls             - Specify the url quantity to run dirsearch and gobuster for dirs and files enumeration [${red}used only with${reset} ${yellow}-d|--domain${reset}]:"
    echo -e "\t\t\t\t        use ${yellow}-l 10${reset} OR ${yellow}--limit-urls 10${reset}"
    echo -e "\t-p  |--proxy                  - This option will use a provided proxy (with port) to avoid or bypass WAF block."
    echo -e "\t-r  |--recon                  - Will execute a recon until you find out what domains are web application: ${red}used only with${reset} ${yellow}-d|--domain${reset}"
    echo -e "\t\t\t\t        The webapp_enum function will be ignored, and the recon execution will be finished."
    echo -e "\t-ro |--report-only            - Opens the read-only app-report dashboard against the existing outputs directory and exits when stopped."
    echo -e "\t\t\t\t        Skips recon entirely — use to re-open the results of a previous scan. Requires ${yellow}collector-results-db${reset} inside ${yellow}output_dir${reset}."
    echo -e "\t\t\t\t        No target flag needed. Ctrl-C, ${yellow}--report-stop${reset}, or ${yellow}docker stop${reset} on the host stops the dashboard and exits."
    echo -e "\t-rs |--report-stop            - Stops a dashboard previously started with ${yellow}-ro|--report-only${reset}."
    echo -e "\t\t\t\t        Sends SIGTERM to the recorded gunicorn pid, waits up to 5s, then SIGKILLs if needed. No-op if nothing is running."
    echo -e "\t-s  |--subdomain-brute        - Specify the wordlist to put in dns_wordlist array and execute gobuster and dnssearch brute force, ${red}used only with${reset} ${yellow}-d|--domain${reset}."
    echo -e "\t\t\t\t        By default the array is empty and not execute amass, gobuster and dnssearch. This option take a long time to finish, use this own your need!"
    echo -e "\t\t\t\t        The success of use those tools is a good wordlist:"
    echo -e "\t\t\t\t        use ${yellow}-s /path/to/wordlist1,/path/to/wordlist2${reset} OR ${yellow}--subdomain-brute /path/to/wordlist1,/path/to/wordlist2${reset}"
    echo -e "\t-u  |--url                    - Specify a valid url [${red}needed${reset}] to retrieve information from specified URL using the webapp_enum function."
    echo -e "\t-vv |--vhost-validation       - Will execute vhost_check and vhost_probe against live IPs to discover virtual hosts."
    echo -e "\t\t\t\t        ${red}used only with${reset} ${yellow}-d|--domain${reset} and ${yellow}-wd|--webapp-discovery${reset}. Without this flag, vhost checks are skipped."
    echo -e "\t-wc |--webapp-crawler         - Will execute web application crawler to get js files and look for url parameters${reset},"
    echo -e "\t-wd |--webapp-discovery       - Will execute the function webapp_alive, ${yellow}execute only with the -r|--recon and -wsd|--webapp-short-detection or --wld|--webapp-long-detections options${reset},"
    echo -e "\t                                without this option the collector will reduce time execution and receive only domains and subdomains"
    echo -e "\t-we |--webapp-enum            - By default, a function called webapp_enum will be executed, ${red}unless${reset} the collector is run recon-only option (${yellow}-r${reset} OR ${yellow}--recon${reset})."
    echo -e "\t\t\t\t        After the use the collector with the recon-only option (${yellow}-r${reset} OR ${yellow}--recon${reset}) you can use this option (${yellow}-we${reset} OR ${yellow}--web-enum${reset}) retrieve information from the web application:"
    echo -e "\t\t\t\t        ${red}used only with${reset} ${yellow}-d|--domain${reset}"
    echo -e "\t-ws |--webapp-scan            - Will execute web application scan with nuclei and acunetix${reset},"
    echo -e "\t-wld|--webapp-long-detection  - Will execute the long list of ports setup in collector.cfg as variable web_port_long_detection."
    echo -e "\t-wsd|--webapp-short-detection - Will execute the short list of ports setup in collector.cfg as variable web_port_short_detection."
    echo -e "\t-ww |--webapp-wordlists       - Specity more wordlists to put in web_wordlist array as the first wordlist to enumerate dirs and files from website."
    echo -e "\t\t\t\t        use ${yellow}-ww /path/to/wordlist1,/path/to/wordlist2${reset} OR ${yellow}--web-wordlists /path/to/wordlist1,/path/to/wordlist2${reset}"
    echo ""
    echo "Notes:"
    echo -e "\t- To stop a running collector, use ${yellow}docker stop <container>${reset} on the host."
    echo -e "\t- To remove a target's results, ${yellow}rm -rf${reset} the corresponding directory on the host."
    echo -e "\t- Output directory is fixed at ${yellow}/opt/collector/outputs${reset} inside the container."
    echo -e "\t  To control where results land on the host, change the ${yellow}-v <host_path>:/opt/collector/outputs${reset} mount in collector-docker / docker run."
    echo ""
    ) 1>&2; exit 1
}

