# Script usage description
usage(){
    (
    echo "Basic usage:"
    echo -e "       ${yellow}$0${reset} ${green}-d domain.com --recon${reset}"
    echo -e "       ${yellow}$0${reset} ${green}-dl /path/file/domain_list.txt --recon${reset}"
    echo -e "       ${yellow}$0${reset} ${green}-u http://domain.com --webapp-wordlists /path/file/wordlist.txt${reset}"
    echo ""
    echo "Options: "
    echo -e "\t-d  |--domain                 - Specify a valid domain [${red}needed${reset}]."
    echo -e "\t-dl |--domain-list            - Specify a valid domain [${red}needed${reset}]."
    echo -e "\t-ed |--exclude-domain         - Specify excluded subdomains after all treated files, ${red}used only with${reset} ${yellow}-d|--domain${reset}:"
    echo -e "\t\t\t\t        use ${yellow}-e domain1.com,domain2.com${reset} OR ${yellow}--exclude-domains domain1.com,domain2.com${reset}"
    echo -e "\t-el |--exclude-domain-list    - Specify excluded subdomains from a file after all treated files, ${red}used only with${reset} ${yellow}-d|--domain${reset} or ${yellow}-dl|--domain-list${reset}:"
    echo -e "\t\t\t\t        use ${yellow}-el /path/file/excluded_domains_list.txt${reset} OR ${yellow}--exclude-domain-list /path/file/excluded_domains_list.txt${reset}"
    echo -e "\t-k  |--kill                   - Will kill the current execution of collector, you need to specify the domain as argument."
    echo -e "\t-kr |--kill-remove            - Will kill the current execution of collector and delete the directory of results from current execution, you need to specify the domain as argument."
    echo -e "\t-l  |--limit-urls             - Specify the url quantity to run dirsearch and gobuster for dirs and files enumeration [${red}used only with${reset} ${yellow}-d|--domain${reset}]:"
    echo -e "\t\t\t\t        use ${yellow}-l 10${reset} OR ${yellow}--limit-urls 10${reset}"
    echo -e "\t-o  |--output                 - This option when specified will use the directory to save the output of collector script if omitted the default value is: ${yellow}${collector_path}${reset}"
    echo -e "\t\t\t\t        This option as well as others can be configured on collector.cfg, variable output_dir or use the parameters like:"
    echo -e "\t\t\t\t        use ${yellow}-o /path/of/output${reset} OR ${yellow}--output-dir /path/of/output${reset}"
    echo -e "\t-p  |--proxy                  - This option will use a provided proxy (with port) to avoid or bypass WAF block."
    echo -e "\t-r  |--recon                  - Will execute a recon until you find out what domains are web application: ${red}used only with${reset} ${yellow}-d|--domain${reset}"
    echo -e "\t\t\t\t        The webapp_enum function will be ignored, and the recon execution will be finished."
    echo -e "\t-s  |--subdomain-brute        - Specify the wordlist to put in dns_wordlist array and execute gobuster and dnssearch brute force, ${red}used only with${reset} ${yellow}-d|--domain${reset}."
    echo -e "\t\t\t\t        By default the array is empty and not execute amass, gobuster and dnssearch. This option take a long time to finish, use this own your need!"
    echo -e "\t\t\t\t        The success of use those tools is a good wordlist:"
    echo -e "\t\t\t\t        use ${yellow}-s /path/to/wordlist1,/path/to/wordlist2${reset} OR ${yellow}--subdomain-brute /path/to/wordlist1,/path/to/wordlist2${reset}"
    echo -e "\t-u  |--url                    - Specify a valid url [${red}needed${reset}] to retrieve information from specified URL using the webapp_enum function."
    echo -e "\t-wc |--webapp-crawler         - Will execute web application crawler to get js files and look for url parameters${reset},"
    echo -e "\t-wd |--webapp-discovery       - Will execute the function webapp_alive, ${yellow}execute only with the -r|--recon and -wsd|--webapp-short-detection or --wld|--webapp-long-detections options${reset},"
    echo -e "\t                                without this option the collector will reduce time execution and receive only domains and subdomains"
    echo -e "\t-we |--webapp-enum            - By default, a function called webapp_enum will be executed, ${red}unless${reset} the collector is run recon-only option (${yellow}-r${reset} OR ${yellow}--recon${reset})."
    echo -e "\t\t\t\t        After the use the collector with the recon-only option (${yellow}-r${reset} OR ${yellow}--recon${reset}) you can use this option (${yellow}-we${reset} OR ${yellow}--web-enum${reset}) retrieve information from the web application:"
    echo -e "\t\t\t\t        ${red}used only with${reset} ${yellow}-d|--domain${reset}"
    echo -e "\t-ws |--webapp-scan            - Will execute web application scan with nuclei and acunetix${reset},"
    echo -e "\t-wld|--webapp-long-detection  - Will execute the long list of ports setup in collector.cfg as variable web_port_long_detection." 
    echo -e "\t-wsd|--webapp-short-detection - Will execute the short list of ports setup in collector.cfg as variable web_port_short_detection."
    echo -e "\t-ww |--webapp-wordlists       - Specity more wordlists to put in web_wordlist array as the first wordlist to enumerate dirs and files from website."
    echo -e "\t\t\t\t        use ${yellow}-ww /path/to/wordlist1,/path/to/wordlist2${reset} OR ${yellow}--web-wordlists /path/to/wordlist1,/path/to/wordlist2${reset}"
    echo ""
    ) 1>&2; exit 1
}

