#!/bin/bash
#######################################################
#                                                     #
# collector is my script for reconnaissance during    #
# my job as pentester or as a hobby doing bug bounty  #
#                                                     #
#######################################################

collector_command_line="$0 $*"
collector_path=$(dirname "$0")

[[ -s "${collector_path}/functions/utils.sh" ]] && source "${collector_path}/functions/utils.sh"
banner
reset_vars

if [ -s "${collector_path}/collector.cfg" ]; then
    source "${collector_path}/collector.cfg"
else
    banner
    echo -e "Please ${red}make sure${reset} you have the ${yellow}collector.cfg${reset} file."
    echo -e "${yellow}You need this to set the tools parameters${reset}!"
    echo -e "You will set aquatone, gobuster, dirsearch threads and others.\n"
    exit 1
fi

# Checking if the essencial functions there are
for file in kill_collector.sh check_binaries.sh usage.sh message.sh menu.sh check_structure.sh \
    check_execution.sh domains_sources.sh files.sh diff.sh infra.sh webapp_crawler.sh \
    webapp_discovery.sh webapp_scan.sh webapp_enum.sh git.sh domains_recon.sh url_recon.sh; do
    function="${collector_path}/functions/${file}"
    if [ -s "${function}" ]; then
        source "${function}"
    else
        echo -e "Please ${red}make sure${reset} you have the ${yellow}\"${function}\"${reset} file."
        echo -e "${yellow}You need this file to execute collector${reset}!"
        echo -e "The collector execution ${red}failed${reset} at ${yellow}$(date +"%Y%m%d %H:%M")${reset} due missing essentials files!" 
        exit 1
    fi
done

check_container
check_binaries

[[ $# -eq 0 ]] && { echo -e "You're using the collector without parameters.\n" ; usage ; } || menu "$@"

check_execution
check_parameter_conflicts
check_parameter_dependency
check_directory_permission

if [[ "${kill_check}" == "yes" ]]; then
    kill_collector "${domain}"
fi

if [[ "${killremove_check}" == "yes" ]]; then
    kill_collector "${domain}"
fi

if [[ "${domain_check}" == "yes" && -n "${domain}" ]]; then
    collector_acquire_lock "${domain}"
    check_is_known_target "${domain}"
    create_directory_structure
    domains_recon
    exit 0
fi

if  [[ "${domainlist_check}" == "yes" && -s "${domain_list}" ]]; then
    unset domain
    while read -r domain; do
        # Skip blank lines and comments, and reject malformed entries instead
        # of letting them flow into URLs and filesystem paths.
        [[ -z "${domain}" || "${domain}" =~ ^[[:space:]]*# ]] && continue
        domain="${domain//[[:space:]]/}"
        if ! validate_domain "${domain}"; then
            echo -e "${yellow}$(date +"%d/%m/%Y %H:%M")${reset} ${red}>>${reset} Skipping invalid domain from ${domain_list}: ${domain}"
            continue
        fi
        # In list mode the lock is acquired/released per-target via a
        # subshell so flock's FD goes out of scope when the target finishes.
        (
            collector_acquire_lock "${domain}"
            check_is_known_target "${domain}"
            create_directory_structure
            domains_recon
        )
    done < "${domain_list}"
    exit 0
fi

if [[ "${url_check}" == "yes" && -n "${url_verify}" ]]; then
    collector_acquire_lock "${url_domain}"
    check_is_known_target "${url_domain}"
    create_directory_structure
    url_recon
fi
