#!/bin/bash
#
# collector my script for reconnaissance during
# my job as pentester or as a hobby doing bug bounty
#

collector_command_line="$0 $*"

[[ -s "${PWD}/functions/banner.sh" ]] && \
    source "${PWD}/functions/banner.sh"
banner

collector_path=$(dirname "$0")

if [ -s "${collector_path}/collector.cfg" ]; then
    source "${collector_path}/collector.cfg"
else
    banner
    echo -e "Please ${red}make sure${reset} you have the ${yellow}collector.cfg${reset} file."
    echo -e "${yellow}You need this to set the tools parameters${reset}!"
    echo -e "You will set aquatone, gobuster, dirsearch threads and others.\n"
    exit 1
fi

[[ -s "${PWD}/functions/check_binaries.sh" ]] && source "${PWD}/functions/check_binaries.sh"
[[ -s "${PWD}/functions/help.sh" ]] && source "${PWD}/functions/help.sh"
[[ -s "${PWD}/functions/kill_collector.sh" ]] && source "${PWD}/functions/kill_collector.sh"
[[ -s "${PWD}/functions/menu.sh" ]] && source "${PWD}/functions/menu.sh"
menu
[[ -s "${PWD}/functions/check_execution.sh" ]] && source "${PWD}/functions/check_execution.sh"
[[ -s "${PWD}/functions/check_structure.sh" ]] && source "${PWD}/functions/check_structure.sh"
[[ -s "${PWD}/functions/check_functions.sh" ]] && source "${PWD}/functions/check_functions.sh"
[[ -s "${PWD}/functions/message.sh" ]] && source "${PWD}/functions/message.sh"
[[ -s "${PWD}/functions/domains_recon.sh" ]] && source "${PWD}/functions/domains_recon.sh"
[[ -s "${PWD}/functions/url_recon.sh" ]] && source "${PWD}/functions/url_recon.sh"
[[ -s "${PWD}/functions/collector_execution.sh" ]] && source "${PWD}/functions/collector_exec.sh"
collector_exec
